version: '3'
services:
  caseprocessor:
    container_name: caseprocessor
    image: eu.gcr.io/census-rm-ci/rm/census-rm-case-processor
    external_links:
     - postgres
     - rabbitmq
     - uacqid
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - SPRING_RABBITMQ_HOST=${RABBIT_HOST}
     - SPRING_RABBITMQ_PORT=${RABBIT_PORT}
     - UACSERVICE_CONNECTION_HOST=${UAC_HOST}
     - UACSERVICE_CONNECTION_PORT=${UAC_PORT}
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "find", "/tmp/case-service-healthy", "-mmin", "-1"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  actionscheduler:
    container_name: actionscheduler
    image: eu.gcr.io/census-rm-ci/rm/census-rm-action-scheduler
    ports:
     - "${ACTION_SCHEDULER_PORT}:8301"
    external_links:
     - postgres
     - rabbitmq
     - redis
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - SPRING_RABBITMQ_HOST=${RABBIT_HOST}
     - SPRING_RABBITMQ_PORT=${RABBIT_PORT}
     - REDIS_HOST=${REDIS_HOST}
     - JAVA_OPTS=-Xmx512m
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8301/actuator/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  actionexporter:
    container_name: actionexporter
    image: eu.gcr.io/census-rm-ci/rm/census-rm-actionexportersvc
    ports:
     - "${ACTIONEXP_PORT}:8141"
     - "${ACTIONEXP_DEBUG_PORT}:5141"
     - "${ACTIONEXP_MAN_PORT}:8241"
    external_links:
     - postgres
     - rabbitmq
     - redis
     - sftp
    environment:
     - SECURITY_BASIC_ENABLED=true
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - LIQUIBASE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}
     - RABBITMQ_HOST=${RABBIT_HOST}
     - RABBITMQ_PORT=${RABBIT_PORT}
     - REDIS_HOST=${REDIS_HOST}
     - SFTP_HOST=${SFTP_HOST}
     - SFTP_PORT=${SFTP_PORT}
     - DATA_GRID_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
     - JAVA_OPTS=-Xmx128m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=${ACTIONEXP_DEBUG_PORT}
     - FREEMARKER_DELAYFORNEWTEMPLATES=3600000
     - DATA_GRID_LOCK_TIME_TO_LIVE_SECONDS=45
     - LIQUIBASE_USER=${POSTGRES_USERNAME}
     - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
     - LOGGING_LEVEL_uk.gov.ons.ctp.response.action.export.scheduled=WARN
     - EXPORT_SCHEDULE_CRON_EXPRESSION=*/5 * * * * *
     - SPRING_ZIPKIN_ENABLED=true
     - SPRING_ZIPKIN_BASEURL=http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8141/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  uacqid:
    container_name: uacqid
    image: eu.gcr.io/census-rm-ci/rm/census-rm-uac-qid-service
    ports:
     - "${UAC_PORT}:8164"
    external_links:
     - postgres
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - JAVA_OPTS=-Xmx128m -Xdebug -Dspring.profiles.active=dev
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8164/actuator/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  pubsub:
    container_name: pubsub
    image: eu.gcr.io/census-rm-ci/rm/census-rm-pubsub
    external_links:
      - rabbitmq
      - pubsub-emulator
    environment:
      - RABBIT_AMQP=amqp://guest:guest@${RABBIT_HOST}:${RABBIT_PORT}
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_PORT=${RABBIT_PORT}
      - SUBSCRIPTION_PROJECT_ID=${SUBSCRIPTION_PROJECT_ID}
      - RECEIPT_TOPIC_PROJECT_ID=${RECEIPT_TOPIC_PROJECT_ID}
      - PUBSUB_EMULATOR_HOST=${PUBSUB_EMULATOR_HOSTNAME}:${PUBSUB_EMULATOR_PORT}
      - RABBIT_QUEUE=${RABBIT_QUEUE}
      - RABBIT_ROUTE=${RABBIT_ROUTE}
      - RABBIT_EXCHANGE=${RABBIT_EXCHANGE}
      - RECEIPT_TOPIC_NAME=${RECEIPT_TOPIC_NAME}
      - SUBSCRIPTION_NAME=${SUBSCRIPTION_NAME}
    restart: always

  caseapi:
    container_name: caseapi
    image: eu.gcr.io/census-rm-ci/rm/census-rm-case-api
    ports:
      - "${CASE_API_PORT}:8161"
    external_links:
     - postgres
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8161/actuator/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    

networks:
  default:
    external:
      name: censusrmdockerdev_default
