version: '3'
services:

  caseprocessor:
    container_name: caseprocessor
    image: eu.gcr.io/census-rm-ci/rm/census-rm-case-processor
    external_links:
     - postgres
     - rabbitmq
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - SPRING_RABBITMQ_HOST=${RABBIT_HOST}
     - SPRING_RABBITMQ_PORT=${RABBIT_PORT}
     - IACSERVICE_CONNECTION_HOST=${IAC_HOST}
     - IACSERVICE_CONNECTION_PORT=${IAC_PORT}
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
     - JAVA_OPTS=-Dspring.profiles.active=dev
    healthcheck:
      test: ["CMD", "find", "/tmp/case-service-healthy", "-mmin", "-1"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  action-scheduler:
    container_name: action-scheduler
    image: eu.gcr.io/census-rm-ci/rm/census-rm-action-scheduler
    ports:
     - "${ACTION_PORT}:8151"
    external_links:
     - postgres
     - rabbitmqs
    environment:
     - SERVER_PORT=${ACTION_PORT}
     - SPRING_RABBITMQ_HOST=${RABBIT_HOST}
     - SPRING_RABBITMQ_PORT=${RABBIT_PORT}
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "find", "/tmp/action-scheduler-healthy", "-mmin", "-1"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  actionexporter:
    container_name: actionexporter
    image: eu.gcr.io/census-rm-ci/rm/census-rm-actionexportersvc
    ports:
     - "${ACTIONEXP_PORT}:8141"
     - "${ACTIONEXP_DEBUG_PORT}:5141"
     - "${ACTIONEXP_MAN_PORT}:8241"
    external_links:
     - postgres
     - rabbitmq
     - redis
     - sftp
    environment:
     - SECURITY_BASIC_ENABLED=true
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - LIQUIBASE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}
     - RABBITMQ_HOST=${RABBIT_HOST}
     - RABBITMQ_PORT=${RABBIT_PORT}
     - REDIS_HOST=${REDIS_HOST}
     - SFTP_HOST=${SFTP_HOST}
     - SFTP_PORT=${SFTP_PORT}
     - DATA_GRID_ADDRESS=${REDIS_HOST}:${REDIS_PORT}
     - JAVA_OPTS=-Xmx128m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=${ACTIONEXP_DEBUG_PORT}
     - FREEMARKER_DELAYFORNEWTEMPLATES=3600000
     - DATA_GRID_LOCK_TIME_TO_LIVE_SECONDS=45
     - LIQUIBASE_USER=${POSTGRES_USERNAME}
     - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
     - LOGGING_LEVEL_uk.gov.ons.ctp.response.action.export.scheduled=WARN
     - EXPORT_SCHEDULE_CRON_EXPRESSION=*/30 * * * * *
     - SPRING_ZIPKIN_ENABLED=true
     - SPRING_ZIPKIN_BASEURL=http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8141/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  iac:
    container_name: iac
    image: eu.gcr.io/census-rm-ci/rm/census-rm-iacsvc
    ports:
     - "${IAC_PORT}:8121"
     - "${IAC_DEBUG_PORT}:5121"
     - "${IAC_MAN_PORT}:8221"
    external_links:
     - postgres
     - rabbitmq
     - redis
    environment:
     - SECURITY_BASIC_ENABLED=true
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
     - LIQUIBASE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}
     - RABBITMQ_HOST=${RABBIT_HOST}
     - RABBITMQ_PORT=${RABBIT_PORT}
     - REDIS_HOST=${REDIS_HOST}
     - CASE_SVC_CONNECTION_CONFIG_HOST=${CASE_HOST}
     - CASE_SVC_CONNECTION_CONFIG_PORT=${CASE_PORT}
     - JAVA_OPTS=-Xmx128m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=${IAC_DEBUG_PORT} -Dspring.profiles.active=dev
     - LIQUIBASE_USER=${POSTGRES_USERNAME}
     - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
     - SPRING_ZIPKIN_ENABLED=true
     - SPRING_ZIPKIN_BASEURL=http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8121/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  pubsub:
    container_name: pubsub
    image: eu.gcr.io/census-rm-ci/rm/census-rm-pubsub
    external_links:
      - rabbitmq
      - pubsub-emulator
    environment:
      - RABBIT_AMQP=amqp://guest:guest@${RABBIT_HOST}:${RABBIT_PORT}
      - SUBSCRIPTION_PROJECT_ID=${SUBSCRIPTION_PROJECT_ID}
      - RECEIPT_TOPIC_PROJECT_ID=${RECEIPT_TOPIC_PROJECT_ID}
      - PUBSUB_EMULATOR_HOST=${PUBSUB_EMULATOR_HOSTNAME}:${PUBSUB_EMULATOR_PORT}
      - RABBIT_QUEUE=${RABBIT_QUEUE}
      - RABBIT_ROUTE=${RABBIT_ROUTE}
      - RABBIT_EXCHANGE=${RABBIT_EXCHANGE}
      - RECEIPT_TOPIC_NAME=${RECEIPT_TOPIC_NAME}
      - SUBSCRIPTION_NAME=${SUBSCRIPTION_NAME}
    restart: always

networks:
  default:
    external:
      name: censusrmdockerdev_default
