exchanges:
- name: action-case-exchange
  type: direct
- name: action-outbound-exchange
  type: direct
- name: adapter-outbound-exchange
  type: direct
- name: delayedRedeliveryExchange
  type: headers
- name: events
  type: topic
- name: notify.enriched.fulfilment.exchange
  type: direct
- name: quarantineExchange
  type: headers
- name: uac-qid-created-exchange
  type: direct
queues:
- name: Action.Field
- name: Action.Printer
- name: Case.Responses
- name: FieldworkAdapter.Refusals
- name: FieldworkAdapter.invalidAddress
- name: FieldworkAdapter.uacUpdated
- name: RM.Field
- name: RM.Field.Test
- name: action.events
- name: action.fulfilment
- name: action.undeliveredMailQueue
- name: case.action
- name: case.ccsPropertyListedQueue
- name: case.fulfilments
- name: case.invalidAddressQueue
- name: case.questionnairelinked
- name: case.refusals
- name: case.rh.case
- name: case.rh.case.test
- name: case.rh.uac
- name: case.rh.uac.test
- name: case.sample.inbound
- name: case.uac-qid-created
- name: case.undeliveredMailQueue
- name: delayedRedeliveryQueue
  arguments:
    x-dead-letter-exchange: ''
    x-message-ttl: 15000
- name: notify.enriched.fulfilment
- name: notify.fulfilments
- name: quarantineQueue
- name: survey.launched
- name: unaddressedRequestQueue
bindings:
- destinationQueue: action.events
  sourceExchange: action-case-exchange
- destinationQueue: Action.Field
  routingKey: Action.Field.binding
  sourceExchange: action-outbound-exchange
- destinationQueue: Action.Printer
  routingKey: Action.Printer.binding
  sourceExchange: action-outbound-exchange
- destinationQueue: RM.Field
  sourceExchange: adapter-outbound-exchange
- destinationQueue: RM.Field.Test
  sourceExchange: adapter-outbound-exchange
- destinationQueue: delayedRedeliveryQueue
  sourceExchange: delayedRedeliveryExchange
- destinationQueue: Case.Responses
  routingKey: event.response.receipt
  sourceExchange: events
- destinationQueue: FieldworkAdapter.Refusals
  routingKey: event.respondent.refusal
  sourceExchange: events
- destinationQueue: FieldworkAdapter.invalidAddress
  routingKey: event.case.address.update
  sourceExchange: events
- destinationQueue: FieldworkAdapter.uacUpdated
  routingKey: event.uac.update
  sourceExchange: events
- destinationQueue: action.fulfilment
  routingKey: event.fulfilment.request
  sourceExchange: events
- destinationQueue: action.undeliveredMailQueue
  routingKey: event.fulfilment.undelivered
  sourceExchange: events
- destinationQueue: case.action
  routingKey: event.case.*
  sourceExchange: events
- destinationQueue: case.action
  routingKey: event.uac.*
  sourceExchange: events
- destinationQueue: case.ccsPropertyListedQueue
  routingKey: event.ccs.propertylisting
  sourceExchange: events
- destinationQueue: case.fulfilments
  routingKey: event.fulfilment.request
  sourceExchange: events
- destinationQueue: case.invalidAddressQueue
  routingKey: event.case.address.update
  sourceExchange: events
- destinationQueue: case.questionnairelinked
  routingKey: event.questionnaire.update
  sourceExchange: events
- destinationQueue: case.refusals
  routingKey: event.respondent.refusal
  sourceExchange: events
- destinationQueue: case.rh.case
  routingKey: event.case.*
  sourceExchange: events
- destinationQueue: case.rh.case.test
  routingKey: event.case.*
  sourceExchange: events
- destinationQueue: case.rh.uac
  routingKey: event.uac.*
  sourceExchange: events
- destinationQueue: case.rh.uac.test
  routingKey: event.uac.*
  sourceExchange: events
- destinationQueue: case.undeliveredMailQueue
  routingKey: event.fulfilment.undelivered
  sourceExchange: events
- destinationQueue: notify.fulfilments
  routingKey: event.fulfilment.request
  sourceExchange: events
- destinationQueue: survey.launched
  routingKey: event.response.authentication
  sourceExchange: events
- destinationQueue: notify.enriched.fulfilment
  sourceExchange: notify.enriched.fulfilment.exchange
- destinationQueue: quarantineQueue
  sourceExchange: quarantineExchange
- destinationQueue: case.uac-qid-created
  sourceExchange: uac-qid-created-exchange
